
# tasks file for RHEL7-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run against RHEL 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version | version_compare('7', '!=')
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.1 or greater
  when: not ansible_version.full | version_compare('2.1', '>=')
  tags:
      - always

- include: prelim.yml
  become: yes
  tags:
      - prelim_tasks
      - always
      
- import_tasks: prelim_stig.yml
  become: yes
  tags:
      - prelim_tasks

- import_tasks: prelim_stig2.yml
  become: yes
  tags:
      - prelim_tasks

- name: Include CAT I patches
  import_tasks: fix-cat1.yml
  when: rhel7stig_cat1_patch | bool
  tags:
      - cat1
      - high

- name: Include CAT II patches
  import_tasks: fix-cat2.yml
  when: rhel7stig_cat2_patch | bool
  tags:
      - cat2
      - medium

- name: Include CAT III patches
  import_tasks: fix-cat3.yml
  when: rhel7stig_cat3_patch | bool
  tags:
      - cat3
      - low

- include: section1.yml
  become: yes
  when: rhel7cis_section1
  tags:
      - rhel7cis_section1

- include: section2.yml
  become: yes
  when: rhel7cis_section2

- include: section3.yml
  become: yes
  when: rhel7cis_section3

- include: section4.yml
  become: yes
  when: rhel7cis_section4

- include: section5.yml
  become: yes
  when: rhel7cis_section5

- include: section6.yml
  become: yes
  when: rhel7cis_section6

- include: post.yml
  become: yes
  tags:
      - post_tasks
      - always

- include: preflight.yml
  when: cis_apply_level_1_profile or cis_apply_level_2_profile

- include: "level-1.yml"
  become: yes
  when: cis_apply_level_1_profile

- include: "level-2.yml"
  become: yes
  when: cis_apply_level_2_profile
